services:
  backend:
    build:
      context: ./GoHabit-system/backend
    ports:
      - "3000:3000"
    container_name: gohabit-backend
    environment:
      DATABASE_URL: "mysql://app:apppass@mysql:3306/goto"
      JWT_SECRET: "docker-secret-cambiar-en-produccion-min-16"
      JWT_EXPIRES_IN: "7d"
      NODE_ENV: "production"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:3000/api/health" ]
      interval: 15s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./GoHabit-system/frontend
    ports:
      - "8080:80"
    container_name: gohabit-frontend
    depends_on:
      - backend
      - mysql

  mysql:
    image: mysql:8.0
    container_name: gohabit-mysql

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: "rootpass"
      MYSQL_DATABASE: "goto"
      MYSQL_USER: "app"
      MYSQL_PASSWORD: "apppass"

    volumes:
      - mysql_data:/var/lib/mysql # persistencia (tablas/índices/datos)
      - ./GoHabit-system/mysql/conf.d:/etc/mysql/conf.d:ro # configuración extra (.cnf), solo lectura

      # Añadido por Luis 
      - ./GoHabit-system/mysql/init-db:/docker-entrypoint-initdb.d:ro
      - ./GoHabit-system/mysql/init-scripts:/docker-entrypoint-initdb.d:ro # creacion de usuarios-roles-vistas-plugins

    healthcheck:
      # indica cuándo MySQL está "listo"
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpass" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
